export const data = [
    {
      name: "Easton",
      surname: "Bode",
      gender: "Trans*Woman",
      isMarried: false,
    },
    {
      name: "Dovie",
      surname: "Price",
      gender: "Cisgender Male",
      isMarried: true,
    },
    {
      name: "Zackary",
      surname: "Heller",
      gender: "M2F",
      isMarried: true,
    },
    {
      name: "Timmothy",
      surname: "Okuneva",
      gender: "Trans*Person",
      isMarried: false,
    },
    {
      name: "Ernesto",
      surname: "Lind",
      gender: "Transexual Male",
      isMarried: false,
    },
    {
      name: "Lee",
      surname: "Rowe",
      gender: "Transexual Female",
      isMarried: true,
    },
    {
      name: "Ally",
      surname: "Mayert",
      gender: "Female to Male",
      isMarried: false,
    },
    {
      name: "Amara",
      surname: "Stiedemann",
      gender: "Man",
      isMarried: false,
    },
    {
      name: "Kylee",
      surname: "Douglas",
      gender: "Gender neutral",
      isMarried: true,
    },
    {
      name: "Oran",
      surname: "McClure",
      gender: "Gender neutral",
      isMarried: true,
    },
    {
      name: "Bret",
      surname: "Gaylord",
      gender: "Gender Nonconforming",
      isMarried: false,
    },
    {
      name: "Daisha",
      surname: "Ortiz",
      gender: "Hermaphrodite",
      isMarried: false,
    },
    {
      name: "Cale",
      surname: "Sanford",
      gender: "Transexual Person",
      isMarried: true,
    },
    {
      name: "Mabel",
      surname: "Sawayn",
      gender: "Androgynes",
      isMarried: false,
    },
    {
      name: "Lucas",
      surname: "Klein",
      gender: "Gender Nonconforming",
      isMarried: false,
    },
    {
      name: "Alberta",
      surname: "Langworth",
      gender: "Androgynes",
      isMarried: true,
    },
    {
      name: "Dillon",
      surname: "Gulgowski",
      gender: "Female to male transgender man",
      isMarried: false,
    },
    {
      name: "Marcos",
      surname: "Deckow",
      gender: "Transexual Man",
      isMarried: true,
    },
    {
      name: "Marcus",
      surname: "Kuhic",
      gender: "Two-spirit",
      isMarried: true,
    },
    {
      name: "Breanne",
      surname: "Blanda",
      gender: "Cisgender Man",
      isMarried: true,
    },
    {
      name: "Betsy",
      surname: "Heaney",
      gender: "Intersex person",
      isMarried: false,
    },
    {
      name: "Dax",
      surname: "Cruickshank",
      gender: "Trans*Female",
      isMarried: true,
    },
    {
      name: "Maximus",
      surname: "Cormier",
      gender: "Transmasculine",
      isMarried: true,
    },
    {
      name: "Ramona",
      surname: "Mills",
      gender: "Male to female transsexual woman",
      isMarried: true,
    },
    {
      name: "Eleanore",
      surname: "Zemlak",
      gender: "Androgynous",
      isMarried: true,
    },
    {
      name: "Edna",
      surname: "Sawayn",
      gender: "Trans Male",
      isMarried: true,
    },
    {
      name: "Tanner",
      surname: "Breitenberg",
      gender: "F2M",
      isMarried: true,
    },
    {
      name: "Ibrahim",
      surname: "Farrell",
      gender: "Transexual",
      isMarried: false,
    },
    { name: "London", surname: "Mayert", gender: "F2M", isMarried: true },
    {
      name: "Jena",
      surname: "Morissette",
      gender: "Androgynous",
      isMarried: true,
    },
    {
      name: "Aiyana",
      surname: "Wehner",
      gender: "Gender Questioning",
      isMarried: true,
    },
    {
      name: "Abbey",
      surname: "Harvey",
      gender: "Non-binary",
      isMarried: true,
    },
    {
      name: "Dalton",
      surname: "Krajcik",
      gender: "Androgyne",
      isMarried: true,
    },
    {
      name: "Alfonzo",
      surname: "Howell",
      gender: "Trans Male",
      isMarried: true,
    },
    {
      name: "Stanton",
      surname: "Lindgren",
      gender: "Cisgender Woman",
      isMarried: true,
    },
    {
      name: "Zella",
      surname: "Lang",
      gender: "Cisgender",
      isMarried: true,
    },
    {
      name: "Cydney",
      surname: "Christiansen",
      gender: "Cisgender Man",
      isMarried: false,
    },
    {
      name: "Ivory",
      surname: "Hamill",
      gender: "T* man",
      isMarried: false,
    },
    {
      name: "Floyd",
      surname: "Hagenes",
      gender: "Trans Person",
      isMarried: true,
    },
    {
      name: "Violette",
      surname: "Stanton",
      gender: "T* woman",
      isMarried: true,
    },
    {
      name: "Delaney",
      surname: "Mitchell",
      gender: "Intersex man",
      isMarried: false,
    },
    {
      name: "Harmon",
      surname: "Bradtke",
      gender: "Cis Man",
      isMarried: false,
    },
    {
      name: "Hailee",
      surname: "Stokes",
      gender: "Intersex person",
      isMarried: true,
    },
    {
      name: "Mandy",
      surname: "Volkman",
      gender: "Cis Female",
      isMarried: true,
    },
    {
      name: "Margot",
      surname: "Robel",
      gender: "Cis Male",
      isMarried: false,
    },
    {
      name: "Veronica",
      surname: "Herzog",
      gender: "Cis Female",
      isMarried: true,
    },
    {
      name: "Willie",
      surname: "Grimes",
      gender: "Non-binary",
      isMarried: true,
    },
    {
      name: "Earl",
      surname: "Bednar",
      gender: "Polygender",
      isMarried: false,
    },
    {
      name: "Margarita",
      surname: "Kuphal",
      gender: "Gender neutral",
      isMarried: false,
    },
    {
      name: "Ressie",
      surname: "Kassulke",
      gender: "Neutrois",
      isMarried: false,
    },
    {
      name: "Maiya",
      surname: "Marvin",
      gender: "Gender neutral",
      isMarried: true,
    },
    { name: "Price", surname: "Frami", gender: "FTM", isMarried: false },
    {
      name: "Tess",
      surname: "Bernier",
      gender: "Pangender",
      isMarried: false,
    },
    {
      name: "Kenyatta",
      surname: "Kerluke",
      gender: "Cis Male",
      isMarried: false,
    },
    {
      name: "Jena",
      surname: "Hickle",
      gender: "T* man",
      isMarried: true,
    },
    {
      name: "Lamar",
      surname: "Fadel",
      gender: "Trans*Person",
      isMarried: true,
    },
    {
      name: "Kenyon",
      surname: "Balistreri",
      gender: "Trans Man",
      isMarried: false,
    },
    {
      name: "Jesse",
      surname: "Tremblay",
      gender: "Transgender Person",
      isMarried: false,
    },
    {
      name: "Allene",
      surname: "Considine",
      gender: "Intersex man",
      isMarried: true,
    },
    {
      name: "Chauncey",
      surname: "Koss",
      gender: "Cisgender Female",
      isMarried: true,
    },
    {
      name: "Dovie",
      surname: "Hammes",
      gender: "Non-binary",
      isMarried: false,
    },
    {
      name: "Josiah",
      surname: "Schowalter",
      gender: "Gender Fluid",
      isMarried: true,
    },
    {
      name: "Mabelle",
      surname: "Beatty",
      gender: "Transmasculine",
      isMarried: false,
    },
    {
      name: "Tyshawn",
      surname: "Zieme",
      gender: "Trans*Male",
      isMarried: false,
    },
    {
      name: "Connie",
      surname: "Beier",
      gender: "Gender neutral",
      isMarried: true,
    },
    {
      name: "Donny",
      surname: "Hamill",
      gender: "Trans Person",
      isMarried: false,
    },
    {
      name: "Lemuel",
      surname: "Cronin",
      gender: "Cisgender Male",
      isMarried: true,
    },
    {
      name: "Gerardo",
      surname: "Hintz",
      gender: "Trans Female",
      isMarried: false,
    },
    {
      name: "General",
      surname: "Robel",
      gender: "T* woman",
      isMarried: false,
    },
    {
      name: "Bettye",
      surname: "Stoltenberg",
      gender: "Intersex",
      isMarried: false,
    },
    {
      name: "Micheal",
      surname: "Hirthe",
      gender: "Cisgender Woman",
      isMarried: false,
    },
    {
      name: "Monty",
      surname: "Wolf",
      gender: "Female to male trans man",
      isMarried: false,
    },
    {
      name: "Brennan",
      surname: "Powlowski",
      gender: "Intersex person",
      isMarried: false,
    },
    {
      name: "Catherine",
      surname: "Bruen",
      gender: "Asexual",
      isMarried: false,
    },
    {
      name: "Hyman",
      surname: "Kilback",
      gender: "Agender",
      isMarried: false,
    },
    {
      name: "Kaylah",
      surname: "Thiel",
      gender: "Gender Fluid",
      isMarried: true,
    },
    {
      name: "Vicenta",
      surname: "Barrows",
      gender: "Neutrois",
      isMarried: false,
    },
    {
      name: "Berta",
      surname: "Farrell",
      gender: "FTM",
      isMarried: false,
    },
    {
      name: "Leonora",
      surname: "Dibbert",
      gender: "Trans*Man",
      isMarried: true,
    },
    {
      name: "Kellie",
      surname: "Auer",
      gender: "T* woman",
      isMarried: false,
    },
    {
      name: "Ubaldo",
      surname: "Hirthe",
      gender: "Cisgender",
      isMarried: true,
    },
    {
      name: "Lance",
      surname: "Carter",
      gender: "Transexual Male",
      isMarried: true,
    },
    {
      name: "Concepcion",
      surname: "Muller",
      gender: "Gender neutral",
      isMarried: false,
    },
    {
      name: "Dale",
      surname: "Dickinson",
      gender: "Two-spirit person",
      isMarried: true,
    },
    {
      name: "Veronica",
      surname: "Roob",
      gender: "Trans*Female",
      isMarried: false,
    },
    {
      name: "Deontae",
      surname: "Crona",
      gender: "Male to female trans woman",
      isMarried: false,
    },
    {
      name: "Adela",
      surname: "Keebler",
      gender: "Transexual Male",
      isMarried: false,
    },
    {
      name: "Ryley",
      surname: "Medhurst",
      gender: "Trans Male",
      isMarried: true,
    },
    {
      name: "Halle",
      surname: "Kohler",
      gender: "Male to female transsexual woman",
      isMarried: true,
    },
    {
      name: "Garnet",
      surname: "Johnson",
      gender: "Cis Female",
      isMarried: true,
    },
    {
      name: "Billie",
      surname: "Jones",
      gender: "Transexual Male",
      isMarried: false,
    },
    { name: "Asia", surname: "Kihn", gender: "Asexual", isMarried: true },
    {
      name: "Odell",
      surname: "Ward",
      gender: "Transgender Female",
      isMarried: true,
    },
    {
      name: "Casey",
      surname: "Hilpert",
      gender: "Cisgender Man",
      isMarried: true,
    },
    {
      name: "Elyssa",
      surname: "Bradtke",
      gender: "Cisgender Female",
      isMarried: false,
    },
    {
      name: "Boyd",
      surname: "Conroy",
      gender: "Non-binary",
      isMarried: true,
    },
    {
      name: "Casandra",
      surname: "Larkin",
      gender: "Trans*Male",
      isMarried: false,
    },
    {
      name: "Melyssa",
      surname: "Gaylord",
      gender: "Trans*Woman",
      isMarried: false,
    },
    {
      name: "Elsie",
      surname: "Rogahn",
      gender: "Two-spirit",
      isMarried: true,
    },
    {
      name: "Camryn",
      surname: "MacGyver",
      gender: "Two-spirit",
      isMarried: false,
    }
  ];
  
export const nonFlattnedArray = [
  1,
  [2, [3, [4]], 5],
  [6, [7, 8, 9, 10], [11, [12, [13, 14, [15]], [16, 17, 18]]]],
  [19, 20, 21, [22, [23, [24, 25, [26, 27, [28, [29, 30]]]]]]],
];

export const randomArray = [
  37, 43, 98, 36, 74, 83, 60, 72, 36,  5, 33, 74,
  80, 27, 17, 42, 67, 32, 91, 86, 54, 84, 37, 14,
   3, 56, 37, 80, 13, 46, 91, 96, 69, 30, 22, 84,
  89, 67,  5, 10, 47, 46, 85, 88, 90, 25,  9, 10,
  51, 25,  1, 17, 37, 22, 22, 28, 32, 55, 49, 38,
  25, 19, 65, 32, 54, 59, 34, 51, 40, 93, 97, 24,
  38, 45, 75, 58, 40, 90, 90, 99, 71, 19, 66, 11,
  42, 60,  5, 36, 18, 60, 70, 56,  2,  9,  9, 14,
  95, 44, 63, 43
]
